# Gradle runtime
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true

minecraft_version=1.20.1
forge_version=47.2.0
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=guaniao
mod_name=Bird Watching
mod_version=3.1.4

mod_group_id=EdDYON.guaniao
mod_authors=EdDYON
mod_description=\u6211\u53bb\uff01\u54ea\u6765\u7684\u9e1f\uff1f
geckolib_version=4.4.9
