# Gradle runtime
# Use the IDE Gradle JVM or JAVA_HOME; Java 21 is required by the toolchain.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true

minecraft_version=1.21.1
neo_version=21.1.248

mod_id=guaniao
mod_name=Bird Watching
mod_version=3.5.0

mod_group_id=EdDYON.guaniao
mod_authors=EdDYON
mod_description=\u6211\u53bb\uff01\u54ea\u6765\u7684\u9e1f\uff1f
geckolib_version=4.6.6
